import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react'
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aarogya AI",
  description: "Generated by Aarogya AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <SessionProvider>
        <body className={inter.className}>
        <Header/>
          {children}
          {/*  <Footer /> */}
          <Toaster />
        </body>
     </SessionProvider>
    </html>
  );
}
