/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7tQibiuZkZd
 */
'use client'

import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useChat } from "ai/react";

export function Chatbot() {
  const {messages, input, handleInputChange, handleSubmit} = useChat()

  return (
    <div className="h-96 w-full max-w-[700px] ">
      <div className="flex flex-col h-full ">
        <h1 className="text-2xl font-bold p-4 font-serif">
            Aarogya AI
        </h1>
        <div className="flex-grow rounded-lg border p-4">
        {messages.map((m, index) => (

            <div className="flex gap-4 items-start">
                <p className="whitespace-pre-line" key={index}>
                    {m.role === "user" ? "You: " : "Assistant:" }
                </p>
                <p className="whitespace-pre-line text-blck bg-sky-200 p-1 rounded-xl" key={index}>
                    {m.content}
                </p>
            </div>
              
            ))}

        </div>
          
      
        <div className=" flex items-center p-2">
          <form className="flex-1" onSubmit={handleSubmit}>
            <Input placeholder="Type your message here..." value={input} onChange={handleInputChange}  />
            <Button className="ml-2" type="submit" >
                Send
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}